from typing import List, Optional
from pydantic import BaseModel, Field

class ProjectIngest(BaseModel):
    """
    Schema for adding or updating projects in the portfolio database.
    """
    id: Optional[str] = Field(None, description="Unique identifier for the project. If not provided, it will be generated.")
    title: str = Field(..., description="The name of the project.")
    description: str = Field(..., description="Detailed description of the project, including features and architecture.")
    technologies: List[str] = Field(default_factory=list, description="List of technologies, languages, and frameworks used.")
    metrics: Optional[str] = Field(None, description="Quantifiable metrics or achievements (e.g. latency improvements, accuracy).")

class JDAnalysisRequest(BaseModel):
    """
    API request schema for Job Description analysis.
    """
    job_description: str = Field(..., description="The raw text of the job description to analyze.")

class JDExtractedData(BaseModel):
    """
    Structured model representing extracted terms from a job description.
    Used by Agent 1 (JD Extractor) and passed down the pipeline.
    """
    hard_skills: List[str] = Field(..., description="Technical skills, languages, tools, frameworks, and libraries required.")
    soft_skills: List[str] = Field(..., description="Soft skills, team fit, methodologies, and communication requirements.")
    latent_requirements: List[str] = Field(..., description="Latent or structural expectations (e.g., legacy migration, microservice scaling, working in ambiguity).")

class MatchedProject(BaseModel):
    """
    Internal model representing a matched project from the vector store query.
    """
    id: str = Field(..., description="Project ID.")
    title: str = Field(..., description="Project title.")
    description: str = Field(..., description="Project description.")
    technologies: List[str] = Field(..., description="Technologies associated with the project.")
    metrics: Optional[str] = Field(None, description="Performance metrics of the project.")
    similarity_score: float = Field(..., description="Distance or similarity score from vector query.")

class SkillMatch(BaseModel):
    """
    Represents the alignment status of a specific required skill.
    """
    skill: str = Field(..., description="The name of the skill.")
    status: str = Field(..., description="Status of the skill match: 'matched', 'partial', or 'missing'.")
    matching_project: Optional[str] = Field(None, description="The title of the matching project that shows proof of this skill.")

class JDAnalysisResponse(BaseModel):
    """
    API response schema generated by Agent 3 (Synthesis Strategist).
    Adheres strictly to this layout via Gemini structured output.
    """
    alignment_score: int = Field(..., ge=0, le=100, description="Overall compatibility score, from 0 to 100.")
    skills_alignment: List[SkillMatch] = Field(..., description="List matching the job's key skills against the portfolio.")
    skill_gaps: List[str] = Field(..., description="Critical skills in the JD that are not represented in the portfolio.")
    tailored_resume_bullets: List[str] = Field(..., description="3 to 5 ATS-optimized resume bullet points referencing candidate projects, specifically tailored to the target role's keywords.")
    recommended_study_plan: List[str] = Field(..., description="A sequence of concepts or topics to study before the interview to cover the identified skill gaps.")


# ── Agent 4 Schemas (Autonomous Outreach & Networking Agent) ──────────────────

class OutreachTone(str):
    """Enumerated tone options for outreach message generation."""
    PROFESSIONAL = "professional"
    CASUAL = "casual"
    CONFIDENT = "confident"

class OutreachRequest(BaseModel):
    """
    API request schema for the autonomous outreach drafting agent.
    Takes context from the JD Analyzer's output alongside the original JD.
    """
    job_description: str = Field(..., description="The original raw job description text.")
    alignment_score: int = Field(..., ge=0, le=100, description="Compatibility score from Agent 3.")
    tailored_bullets: List[str] = Field(..., description="ATS-optimized resume bullets generated by Agent 3.")
    tone: str = Field(
        default="professional",
        description="Desired tone for the outreach messages. One of: 'professional', 'casual', 'confident'."
    )
    candidate_name: str = Field(
        default="Vansh Agrawal",
        description="The candidate's full name to personalize messages."
    )

class OutreachResponse(BaseModel):
    """
    API response schema for Agent 4 (The Networker).
    Generated via Gemini structured outputs to strictly enforce the layout.
    """
    linkedin_request: str = Field(
        ...,
        max_length=300,
        description="A short, humanized LinkedIn connection request referencing a specific technical match. Hard limit of 300 characters."
    )
    follow_up_message: str = Field(
        ...,
        description="A longer, conversational follow-up email or LinkedIn message requesting a coffee chat or referral. Must reference at least one of the candidate's specific portfolio projects by name."
    )
    subject_line: str = Field(
        ...,
        description="A concise, compelling email subject line for the follow-up message."
    )


# ── Agent 5 Schemas (Career Compass – Resume → Role Strategist) ────────────────

class RolePathway(BaseModel):
    """
    A single suggested career role pathway derived from the candidate's resume.
    Each pathway contains an alignment score and a structured learning roadmap.
    """
    role_title: str = Field(
        ...,
        description="The suggested job title / career pathway (e.g., 'ML Engineer', 'Full-Stack Engineer', 'Data Scientist')."
    )
    current_alignment_score: int = Field(
        ...,
        ge=0,
        le=100,
        description="How closely the candidate's current resume aligns with this role, from 0 to 100."
    )
    core_strengths: List[str] = Field(
        ...,
        min_length=2,
        description="3-5 specific skills or experiences from the resume that make the candidate a strong fit for this role."
    )
    missing_skills_roadmap: List[str] = Field(
        ...,
        min_length=2,
        description="Ordered list of 3-5 skills or technologies the candidate should learn next to unlock this career path."
    )

class CareerCompassResponse(BaseModel):
    """
    API response schema for Agent 5 (The Strategist).
    Returns exactly 3 distinct RolePathway suggestions ranked by alignment_score descending.
    Generated via Gemini structured outputs.
    """
    suggested_roles: List[RolePathway] = Field(
        ...,
        min_length=3,
        max_length=3,
        description="Exactly 3 suggested role pathways, ordered from highest to lowest alignment score."
    )
    resume_summary: str = Field(
        ...,
        description="A 2-3 sentence executive summary of the candidate's profile synthesized from their resume."
    )


# ── Agent 7 Schemas (Salary Intelligence Agent) ───────────────────────────────

class SalaryRequest(BaseModel):
    """
    API request schema for the salary intelligence agent.
    """
    role_title: str = Field(..., description="The target job title (e.g., 'Senior ML Engineer').")
    location: str = Field(..., description="City / region (e.g., 'San Francisco, CA' or 'Remote - USA').")
    experience_level: str = Field(
        ...,
        description="Seniority level: one of 'entry', 'mid', 'senior', 'staff', 'principal'."
    )
    experience_years: int = Field(..., ge=0, le=40, description="Total years of professional experience.")

class CompensationBand(BaseModel):
    """Three-point compensation range in USD per year."""
    p25: int = Field(..., description="25th percentile annual compensation in USD.")
    median: int = Field(..., description="Median (50th percentile) annual compensation in USD.")
    p75: int = Field(..., description="75th percentile annual compensation in USD.")

class SalaryIntelligenceResponse(BaseModel):
    """
    API response schema for Agent 7 (Salary Intelligence Agent).
    Provides compensation bands, negotiation guidance, and market context.
    Generated via Gemini structured outputs.
    """
    base_salary_band: CompensationBand = Field(..., description="Base salary range only (no equity or bonus).")
    total_comp_band: CompensationBand = Field(..., description="Total compensation range including base + average bonus + equity value annualized.")
    equity_range: str = Field(..., description="Typical equity grant range for this role/level (e.g., '$20K–$80K RSUs over 4 years').")
    signing_bonus_range: str = Field(..., description="Typical signing bonus range (e.g., '$5K–$25K one-time').")
    negotiation_floor: int = Field(..., description="Minimum base salary the candidate should accept — below this, walk away.")
    negotiation_ceiling: int = Field(..., description="Aspirational maximum base to anchor the negotiation conversation.")
    negotiation_script: str = Field(..., description="A 3-4 sentence script the candidate can use verbatim when discussing compensation with a recruiter.")
    market_insights: List[str] = Field(..., description="3-5 data-backed insights about the compensation landscape for this role/location/level.")


# ── Agent 8 Schemas (Cover Letter Forge) ─────────────────────────────────────

class CoverLetterRequest(BaseModel):
    """
    API request schema for the cover letter generation agent.
    Accepts JD context from the JD Analyzer and a style preference.
    """
    job_description: str = Field(..., description="The raw job description text.")
    tailored_bullets: List[str] = Field(..., description="Resume bullets from Agent 3 (JD Analyzer) to inject as evidence.")
    alignment_score: int = Field(..., ge=0, le=100, description="Alignment score from Agent 3.")
    candidate_profile: Optional[str] = Field(None, description="The candidate's global profile text, to extract their name and extra details.")
    style: str = Field(
        default="professional",
        description="Writing style: 'professional' (formal + polished), 'story_driven' (narrative arc), or 'data_first' (metrics-led)."
    )
    candidate_name: str = Field(default="Vansh Agrawal", description="Candidate's full name.")
    target_company: str = Field(default="the company", description="Target company name for personalisation.")

class CoverLetterResponse(BaseModel):
    """
    API response schema for Agent 8 (Cover Letter Forge).
    Returns the full letter plus metadata for UI display.
    """
    cover_letter: str = Field(..., description="The complete, ready-to-send cover letter text (400-500 words).")
    word_count: int = Field(..., description="Approximate word count of the generated letter.")
    key_hooks: List[str] = Field(..., description="2-4 power phrases or strongest points used in the letter — surfaced for quick review.")


# ── Agent 6 Schemas (Project Auditor & Explainer Agent) ───────────────────────

class CodeSnippet(BaseModel):
    """
    Represents a single file name and its contents passed in direct paste mode.
    """
    filename: str = Field(..., description="Name of the file (e.g., 'main.py').")
    content: str = Field(..., description="Full text content of the file.")

class ProjectAuditRequest(BaseModel):
    """
    API request schema for auditing a project codebase.
    Can accept a local directory path, direct code snippets, or a public GitHub repository URL.
    """
    local_directory_path: Optional[str] = Field(None, description="Absolute local folder path to scan for code files.")
    code_snippets: Optional[List[CodeSnippet]] = Field(None, description="Pasted code snippets with filenames.")
    github_repo_url: Optional[str] = Field(None, description="A public GitHub repository URL to download and scan.")

class AuditQuestion(BaseModel):
    """
    An interview question and its detailed ideal answer for the audited project.
    """
    question: str = Field(..., description="The interview question (e.g. 'Why did you use React 19?').")
    answer: str = Field(..., description="The structured, professional ideal answer explaining technical details.")

class ProjectAuditResponse(BaseModel):
    """
    API response schema for Agent 6 (Project Auditor).
    Includes architectural summaries, Mermaid diagrams, interview defense Q&A, and resume bullets.
    Generated via Gemini structured outputs.
    """
    project_title: str = Field(..., description="An optimized, professional title for the project.")
    project_description: str = Field(..., description="A concise, high-impact description summarizing what the project does.")
    technologies: List[str] = Field(..., description="List of detected programming languages, libraries, databases, and frameworks.")
    metrics: Optional[str] = Field(None, description="A summary of potential or detected achievements/metrics based on the code's complexity.")
    architecture_overview: str = Field(..., description="A summary explaining the system design, core modules, and data flow of this codebase.")
    mermaid_diagram: str = Field(..., description="A clean, valid Mermaid.js flowchart string (using graph TD or LR) illustrating the module relationships and data flow. Never include markdown wrappers around the string itself.")
    interview_prep_questions: List[AuditQuestion] = Field(..., description="3-5 company interview defense questions tailored to this project's code decisions.")
    resume_bullets: List[str] = Field(..., description="3 tailored Google X-Y-Z formula resume bullets highlighting engineering achievements from this project.")
    code_quality_suggestions: List[str] = Field(..., description="2-3 specific suggestions for code readability, structure, or clean code best practices based on the code.")
    performance_suggestions: List[str] = Field(..., description="2-3 suggestions to improve execution speed, resource leaks, caching, or scaling.")
    security_suggestions: List[str] = Field(..., description="2-3 security best practice recommendations (e.g., credentials management, input validation).")

class ATSScoreResponse(BaseModel):
    """
    API response schema generated by Agent 9 (ATS Scorer).
    """
    match_score: int = Field(..., description="A score from 0 to 100 representing how well the resume matches the JD.")
    matched_keywords: List[str] = Field(..., description="Important keywords from the JD that were successfully found in the resume.")
    missing_keywords: List[str] = Field(..., description="Critical keywords from the JD that are missing from the resume.")
    formatting_feedback: List[str] = Field(..., description="Feedback on resume formatting that might hinder ATS parsing (e.g., complex tables, missing standard sections).")
    overall_verdict: str = Field(..., description="A brief paragraph summarizing the candidate's fit and major actionable advice.")


# ── Agent 10 Schemas (Mock Interview Agent) ──────────────────────────────────

class ConversationTurn(BaseModel):
    """A single turn in the mock interview conversation."""
    role: str = Field(..., description="'interviewer' or 'candidate'")
    content: str = Field(..., description="The message content")

class MockInterviewRequest(BaseModel):
    """
    API request schema for the mock interview agent.
    """
    job_description: str = Field(..., description="The target Job Description.")
    candidate_profile: str = Field(..., description="The candidate's unified profile or resume text.")
    conversation_history: List[ConversationTurn] = Field(default_factory=list, description="The chat history so far. If empty, the agent asks the first question.")
    latest_answer: Optional[str] = Field(None, description="The candidate's latest answer to process.")

class MockInterviewResponse(BaseModel):
    """
    API response schema for Agent 10.
    """
    feedback: Optional[str] = Field(None, description="Constructive feedback on the candidate's latest answer, using STAR method principles where applicable. Null if it's the first question.")
    next_question: str = Field(..., description="The next interview question to ask the candidate.")
    is_technical: bool = Field(..., description="Whether the next question is technical (true) or behavioral (false).")


